In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('tot_data.csv')

In [6]:
board_vec = np.zeros([15*15],dtype='f')

board_data = np.array(df.iloc[0][1:])

In [7]:
board_stack = []

board_mat = board_data.reshape([15,15])

# rotate
board_stack.append(board_mat)
board_stack.append(np.rot90(board_mat))
board_stack.append(np.rot90(board_mat,2))
board_stack.append(np.rot90(board_mat,3))

board_fliplr = np.fliplr(board_mat)
board_flipud = np.flipud(board_mat)

# rotate and filp
board_stack.append(board_fliplr)
board_stack.append(np.rot90(board_fliplr))
board_stack.append(np.rot90(board_fliplr,2))
board_stack.append(np.rot90(board_fliplr,3))

board_stack.append(board_flipud)
board_stack.append(np.rot90(board_flipud))
board_stack.append(np.rot90(board_flipud,2))
board_stack.append(np.rot90(board_flipud,3))

board_stack

[array([[ 0,  0,  0,  0,  0,  0,  0,  0, 38,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0, 37,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0, 28, 35,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0, 26,  0, 27,  0, 44, 45,  0,  0,  0],
        [ 0,  0,  0,  0,  0, 34, 31, 29, 33, 15, 32, 43,  0, 60,  0],
        [ 0,  0,  0,  0,  0, 25, 30,  4, 36, 14, 11, 46,  0, 59,  0],
        [ 0,  0,  0, 57, 24, 17,  6,  3, 13, 10, 54, 50, 61, 55,  0],
        [ 0,  0,  0,  0,  0,  7, 16,  1,  8, 12, 53, 62, 56,  0,  0],
        [ 0,  0,  0,  0,  0, 20, 21,  2,  5, 52, 47, 49, 51,  0,  0],
        [ 0,  0, 72,  0, 58,  9, 18,  0,  0, 23, 41, 42,  0,  0,  0],
        [ 0,  0,  0,  0, 22, 19, 66, 39, 40,  0, 48,  0,  0,  0,  0],
        [ 0,  0, 73,  0,  0, 63,  0, 64,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 65, 67, 69, 70, 71,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, 68,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,

In [8]:
board_size = 15
board_x_stack = []
board_y_stack = []


board_vec = board_stack[0].flatten() # 한 판의 결과를 (255,) 형태의 vector로
max_step = np.max(board_vec)
    
for data_cnt in range(1,int(max_step)): # 1~max_step
    board_x = np.zeros([board_size*board_size],dtype='f')
    board_y = np.zeros([board_size*board_size],dtype='f')
    
    for i in range(len(board_vec)): # 오목판의 각 좌표를 추출

        if data_cnt%2 != 0: #흑 player
            if board_vec[i] > 0 and board_vec[i] <= data_cnt: # 뽑아온 좌표가 n번째 착수 이전
                if board_vec[i]%2 != 0:
                    board_x[i] = 1 # 흑이면 X data에 1을 기입
                else:
                    board_x[i] = 2 # 백이면 X data에 2를 기입

            if board_vec[i] == data_cnt + 1: # 뽑아온 좌표가 n+1번째 착수일 경우
                board_y[i] = 1 # Y data에 1을 기입

        else:
            if board_vec[i] > 0 and board_vec[i] <= data_cnt:
                if board_vec[i]%2 == 0:
                    # 백
                    board_x[i] = 1
                else:
                    board_x[i] = 2

            if board_vec[i] == data_cnt + 1: 
                board_y[i] = 1     

    if (np.sum(board_y)) != 1:
        print('학습데이터에 문제가 있습니다.')

    board_x_stack.append(board_x/2)
    board_y_stack.append(board_y)
    
print(len(board_x_stack))
print(len(board_y_stack))

72
72


In [9]:
board_x_stack
x_stack_li = []
for i in board_x_stack:
    x_stack = np.array(i).reshape(15,15)
    x_stack_li.append(x_stack)

for i in x_stack_li:
    print(i)

[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [10]:
board_y_stack
y_stack_li = []
for i in board_y_stack:
    y_stack = np.array(i).reshape(15,15)
    y_stack_li.append(y_stack)

for i in y_stack_li:
    print(i)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0