In [1]:
import pandas as pd

df = pd.read_csv('tot_data.csv')
df = df.drop('Unnamed: 0', axis=1)

In [2]:
df

1  2  3  4  5  6  7  8   9  10  ...  216  217  218  219  220  221  222  \
0      0  0  0  0  0  0  0  0  38   0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0   0   0  ...    0    0   51   52   54    0    0   
...   .. .. .. .. .. .. .. ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...   
37695  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   
37696  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   
37697  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   
37698  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   
37699  0  0  0  0  0  0  0  0   0   0  ...    0    0    0    0    0    0    0   

       223  224  225  
0        0    0    0  
1        0    0    0  
2        0    0    0  
3        0    0    0  
4        0    0    0  
...    ...  ...  ...  
37695    0    0    0  
37696    0    0    0  
37697    0    0    0  
37698    0    0    0  
37699    0    0    0  

[37700 rows x 225 columns]

In [3]:
print([i for i in df.iloc[0]])

[0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 0, 27, 0, 44, 45, 0, 0, 0, 0, 0, 0, 0, 0, 34, 31, 29, 33, 15, 32, 43, 0, 60, 0, 0, 0, 0, 0, 0, 25, 30, 4, 36, 14, 11, 46, 0, 59, 0, 0, 0, 0, 57, 24, 17, 6, 3, 13, 10, 54, 50, 61, 55, 0, 0, 0, 0, 0, 0, 7, 16, 1, 8, 12, 53, 62, 56, 0, 0, 0, 0, 0, 0, 0, 20, 21, 2, 5, 52, 47, 49, 51, 0, 0, 0, 0, 72, 0, 58, 9, 18, 0, 0, 23, 41, 42, 0, 0, 0, 0, 0, 0, 0, 22, 19, 66, 39, 40, 0, 48, 0, 0, 0, 0, 0, 0, 73, 0, 0, 63, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 65, 67, 69, 70, 71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [6]:
import numpy as np

def data_15_15(list_data):
    list_data = np.array(list_data)
    new_form = np.reshape(list_data, (15,15))
    
    print(new_form)
    return new_form

In [7]:
form = data_15_15([i for i in df.iloc[0]])

[[ 0  0  0  0  0  0  0  0 38  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 37  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 28 35  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0 27  0 44 45  0  0  0]
 [ 0  0  0  0  0 34 31 29 33 15 32 43  0 60  0]
 [ 0  0  0  0  0 25 30  4 36 14 11 46  0 59  0]
 [ 0  0  0 57 24 17  6  3 13 10 54 50 61 55  0]
 [ 0  0  0  0  0  7 16  1  8 12 53 62 56  0  0]
 [ 0  0  0  0  0 20 21  2  5 52 47 49 51  0  0]
 [ 0  0 72  0 58  9 18  0  0 23 41 42  0  0  0]
 [ 0  0  0  0 22 19 66 39 40  0 48  0  0  0  0]
 [ 0  0 73  0  0 63  0 64  0  0  0  0  0  0  0]
 [ 0  0  0  0 65 67 69 70 71  0  0  0  0  0  0]
 [ 0  0  0  0  0 68  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [8]:
def change_01(new_form):
    print(new_form)
    game_len = np.max(new_form)
    print(game_len)
    for idx1, row in enumerate(new_form):
        for idx2, col in enumerate(row):
            if col == game_len:
                if new_form[idx1, idx2] % 2 == 0:
                    new_form[idx1, idx2] = 4
                else:
                    new_form[idx1, idx2] = 3
            elif col == 0:
                new_form[idx1, idx2] = 0
            elif col % 2 == 0:
                new_form[idx1, idx2] = 2
            else:
                new_form[idx1, idx2] = 1
                
    print(new_form)
    return new_form

In [9]:
new_form = change_01(form)

[[ 0  0  0  0  0  0  0  0 38  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 37  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 28 35  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0 27  0 44 45  0  0  0]
 [ 0  0  0  0  0 34 31 29 33 15 32 43  0 60  0]
 [ 0  0  0  0  0 25 30  4 36 14 11 46  0 59  0]
 [ 0  0  0 57 24 17  6  3 13 10 54 50 61 55  0]
 [ 0  0  0  0  0  7 16  1  8 12 53 62 56  0  0]
 [ 0  0  0  0  0 20 21  2  5 52 47 49 51  0  0]
 [ 0  0 72  0 58  9 18  0  0 23 41 42  0  0  0]
 [ 0  0  0  0 22 19 66 39 40  0 48  0  0  0  0]
 [ 0  0 73  0  0 63  0 64  0  0  0  0  0  0  0]
 [ 0  0  0  0 65 67 69 70 71  0  0  0  0  0  0]
 [ 0  0  0  0  0 68  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
73
[[0 0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 1 0 2 1 0 0 0]
 [0 0 0 0 0 2 1 1 1 1 2 1 0 2 0]
 [0 0 0 0 0 1 2 2 2 2 1 2 0 1 0]
 [0 0 0 1 2 1 2 1 1 2 2 2 1 1 0]
 [0 0 0 0 0 1 2 1 2 2 1 2 2 0 0]
 [0 0 0 0 0 

In [18]:
def col_win(new_form):
    for col in range(15):
        col_list = new_form[:, col]
        if [1,1,1,1,1] in col_list:
            print('1')
        elif [2,2,2,2,2] in col_list:
            print('2')
        else:
            print('nothing')

In [11]:
col_win(new_form)

nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing
nothing


C:\Users\YH\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  after removing the cwd from sys.path.
C:\Users\YH\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  
